import util

WIDTH = 1440
HEIGHT = 720
CENTRE_WIDTH=util.width_prct(75)
CENTRE_HEIGHT=util.height_prct(75)

GRID_SIZE = 20
GRID_HEIGHT = 24
GRID_WIDTH = 72
CELL_COUNT = GRID_SIZE**2
BUTTON_HEIGHT = GRID_HEIGHT//GRID_SIZE
BUTTON_WIDTH = GRID_WIDTH//GRID_SIZE

AMOUNT_MINES = (GRID_SIZE**2)//4

